### PR TITLE
added functions, e.g. airspyhf_lib_gitver_description()

### PR DESCRIPTION
**Pull request by hayguen**
airspyhf_lib_gitver_description(): requires genGitVersion.sh in main folder
  for git bash on windows. automatically runs on Linux with cmake step.
  gives better revision info in programs using unreleased versions of this
  library

airspyhf_IQpairsPerCallback(): does not need to open any device

Signed-off-by: hayati ayguen <h_ayguen@web.de>

### CODE REVIEW

**Comment by csete** [comment]
I use similar tools for generating version in my projects, but IMO it's only relevant for packaging and not so much for application. Alternatively, one could use it to generate the version number, but I think it is a bad idea to have two API calls returning different and potentially inconsistent version numbers/strings.

In any case, the git version generator should have a fall-back for builds done outside of git repository or when the git command is not available.

As for airspyhf_IQpairsPerCallback(), I recommend using the existing naming convention.

**Comment by hayguen** [comment]
i'm going to use the version in the https://github.com/hayguen/ExtIO_AirSpyHFplus.
Unfortunately with the latest big improvement in airspyhf airspyhf_lib_version() still deliver "1.0.0".
However, what would you suggest?

Naming convention: is airspyhf_get_iq_pairs_per_callback() ok?

**Comment by csete** [comment]
> Unfortunately with the latest big improvement in airspyhf airspyhf_lib_version() still deliver "1.0.0".

We just need to poke @touil to update the version numbers and git tags more frequently :)

**Comment by touil** [comment]
Problem solved: https://github.com/airspy/airspyhf/commit/12de1d5e40223e31f71d59ab07caab81e6c3d733

Github is just a mean for distributing code with the rest of the world. I don't use it as my main configuration management system. So, I would prefer to not have yet another dependency in my build chain.

**Comment by hayguen** [comment]
shall i remove airspyhf_lib_gitver_description() and request increasing version number from time to time?

**Comment by touil** [comment]
The version number will be bumped when the API changes. The existing API is still guaranteed to behave the same as before.

**Comment by hayguen** [comment]
increase vom 1.0.0 to 1.1.0 is absolutely ok for me, as there are just additional functions

**Comment by touil** [comment]
All good then.

**Pull request closed without merging**
